Cen:
    Type: Knots

    g:
        sigma: 0.02

    hlr: 1.7
    Flux: 6000.0
    Pos: Fixed
    dx: 0.0
    dy: 0.0
    r: 0.0

    knots:
        num: 100

        # fraction of disk flux

Neigh:
    Type: Knots

    g:
        sigma: 0.02

    hlr: 3.4
    Flux: 8000.
    Pos: Rand_circle
    dx: 15.
    dy: 15.
    r: 15.

    knots:
        num: 100

        # fraction of disk flux

Image:
    Bgrms: 0.1
    Scale: 1
#    dims: [48, 48]

Psf:
    Psf_hlr: 1.7
    Scale: 1.
    Bgrms_psf: 0.0001

Shear:
    Shear1: 0.02
    Shear2: 0.00

Mode: mof
